name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push 5.3/ubuntu/20.04/Dockerfile
        uses: docker/build-push-action@v2
        with:
          file: ./5.3/ubuntu/20.04/Dockerfile
          push: true
          tags: |
            swiftwasm/swift:5.3-focal
            swiftwasm/swift:focal
      - name: Push 5.3/ubuntu/18.04/Dockerfile
        uses: docker/build-push-action@v2
        with:
          file: ./5.3/ubuntu/18.04/Dockerfile
          push: true
          tags: |
            swiftwasm/swift:5.3
            swiftwasm/swift:5.3-bionic
            swiftwasm/swift:bionic
            swiftwasm/swift:latest
