name: Publish Docker image
on:
  push:
    branches: [master]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SWIFTWASM_PERSONAL_TOKEN }}
      - name: Push 5.3/ubuntu/20.04/Dockerfile
        uses: docker/build-push-action@v2
        with:
          file: ./5.3/ubuntu/20.04/Dockerfile
          push: true
          tags: |
            ghcr.io/swiftwasm/swift:5.3-focal
            ghcr.io/swiftwasm/swift:focal
      - name: Push 5.3/ubuntu/18.04/Dockerfile
        uses: docker/build-push-action@v2
        with:
          file: ./5.3/ubuntu/18.04/Dockerfile
          push: true
          tags: |
            ghcr.io/swiftwasm/swift:5.3
            ghcr.io/swiftwasm/swift:5.3-bionic
            ghcr.io/swiftwasm/swift:bionic
            ghcr.io/swiftwasm/swift:latest
